# WEB SCRAPING ASSIGNMENT 4

In [32]:
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.keys import Keys
import warnings
warnings.filterwarnings("ignore")
import time

# QUESTION 1

In [60]:
driver = webdriver.Chrome()
#To load url
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
#To maximize window 
driver.maximize_window()

#creating empty list for all attributes
rank=[]
vid_name=[]
artist=[]
views=[]
upload_date=[]

rank_ele=driver.find_elements(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]/tbody/tr/td[1]")
for i in rank_ele:
    x=i.text.replace('.','')
    rank.append(x)

vid_name_ele=driver.find_elements(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]/tbody/tr/td[2]/a")
for i in vid_name_ele[0:11]:
    x=i.text
    vid_name.append(x)
    
vid_name_ele_1=driver.find_element(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]/tbody/tr/td[2]/i/a")
vid_name.append(vid_name_ele_1.text)

vid_name_ele=driver.find_elements(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]/tbody/tr/td[2]/a")
for i in vid_name_ele[11:]:
    x=i.text
    vid_name.append(x)

artist_ele=driver.find_elements(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]/tbody/tr/td[3]")
for i in artist_ele:
    x=i.text
    artist.append(x)

views_ele=driver.find_elements(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]/tbody/tr/td[4]")
for i in views_ele:
    x=i.text
    views.append(x)

upload_date_ele=driver.find_elements(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]/tbody/tr/td[5]")
for i in upload_date_ele[0:30]:
    x=i.text
    upload_date.append(x)
    
print(rank)
print(vid_name)
print(artist)
print(views)
print(upload_date)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
['Baby Shark Dance', 'Despacito', 'Johny Johny Yes Papa', 'Bath Song', 'Shape of You', 'See You Again', 'Wheels on the Bus', 'Phonics Song with Two Words', 'Uptown Funk', 'Learning Colors – Colorful Eggs on a Farm', 'Gangnam Style', 'Masha and the Bear', 'Dame Tu Cosita', 'Axel F', 'Sugar', 'Counting Stars', 'Roar', 'Baa Baa Black Sheep', 'Waka Waka (This Time for Africa)', 'Lakdi Ki Kathi', 'Sorry', 'Thinking Out Loud', 'Humpty the train on a fruits ride', 'Dark Horse', 'Perfect', 'Let Her Go', 'Faded', 'Shree Hanuman Chalisa', 'Girls Like You', 'Lean On']
["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', "LooLoo Kids - Nursery Rhymes and Children's Songs", 'Cocomelon - Nursery Rhymes', 'Ed Sheeran', 'Wiz Khalifa', 'Cocomelon - Nursery Rhymes', 'ChuChu TV Nursery Rhymes & Kids Songs', 'Mark Ronson', 'Miroshka TV', 'officialpsy', 'Get Movies', 'Ultra Records', 'Crazy Frog', 'Maroon 5', 'OneRepublic', 'Katy Perry', 'Cocomelon - Nursery Rhymes', 'Shakira', 'Jingle Toons', 'Justin Bieber', 'Ed Sheeran', 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs', 'Katy Perry', 'Ed Sheeran', 'Passenger', 'Alan Walker', 'T-Series Bhakti Sagar', 'Maroon 5', 'Major Lazer Official']
['13.65', '8.32', '6.84', '6.50', '6.14', '6.09', '5.71', '5.57', '5.09', '5.01', '4.96', '4.57', '4.48', '4.16', '3.97', '3.92', '3.91', '3.84', '3.78', '3.76', '3.74', '3.69', '3.63', '3.63', '3.60', '3.56', '3.55', '3.54', '3.52', '3.50']
['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'May 2, 2018', 'January 30, 2017', 'April 6, 2015', 'May 24, 2018', 'March 6, 2014', 'November 19, 2014', 'February 27, 2018', 'July 15, 2012', 'January 31, 2012', 'April 5, 2018', 'June 16, 2009', 'January 14, 2015', 'May 31, 2013', 'September 5, 2013', 'June 25, 2018', 'June 4, 2010', 'June 14, 2018', 'October 22, 2015', 'October 7, 2014', 'January 26, 2018', 'February 20, 2014', 'November 9, 2017', 'July 25, 2012', 'December 3, 2015', 'May 10, 2011', 'May 31, 2018', 'March 22, 2015']

In [61]:
print(len(rank),len(vid_name),len(artist),len(views),len(upload_date))

30 30 30 30 30

In [62]:
df = pd.DataFrame({'RANK': rank, 'VIDEO NAME': vid_name, 'ARTIST': artist, 'VIEWS (Billions)': views, 'UPLOAD DATE': upload_date})
df

,RANK,VIDEO NAME,ARTIST,VIEWS (Billions),UPLOAD DATE
0,1,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,13.65,"June 17, 2016"
1,2,Despacito,Luis Fonsi,8.32,"January 12, 2017"
2,3,Johny Johny Yes Papa,LooLoo Kids - Nursery Rhymes and Children's Songs,6.84,"October 8, 2016"
3,4,Bath Song,Cocomelon - Nursery Rhymes,6.50,"May 2, 2018"
4,5,Shape of You,Ed Sheeran,6.14,"January 30, 2017"
5,6,See You Again,Wiz Khalifa,6.09,"April 6, 2015"
6,7,Wheels on the Bus,Cocomelon - Nursery Rhymes,5.71,"May 24, 2018"
7,8,Phonics Song with Two Words,ChuChu TV Nursery Rhymes & Kids Songs,5.57,"March 6, 2014"
8,9,Uptown Funk,Mark Ronson,5.09,"November 19, 2014"
9,10,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,5.01,"February 27, 2018"
10,11,Gangnam Style,officialpsy,4.96,"July 15, 2012"
11,12,Masha and the Bear,Get Movies,4.57,"January 31, 2012"
12,13,Dame Tu Cosita,Ultra Records,4.48,"April 5, 2018"
13,14,Axel F,Crazy Frog,4.16,"June 16, 2009"
14,15,Sugar,Maroon 5,3.97,"January 14, 2015"
15,16,Counting Stars,OneRepublic,3.92,"May 31, 2013"
16,17,Roar,Katy Perry,3.91,"September 5, 2013"
17,18,Baa Baa Black Sheep,Cocomelon - Nursery Rhymes,3.84,"June 25, 2018"
18,19,Waka Waka (This Time for Africa),Shakira,3.78,"June 4, 2010"
19,20,Lakdi Ki Kathi,Jingle Toons,3.76,"June 14, 2018"
20,21,Sorry,Justin Bieber,3.74,"October 22, 2015"
21,22,Thinking Out Loud,Ed Sheeran,3.69,"October 7, 2014"
22,23,Humpty the train on a fruits ride,Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.63,"January 26, 2018"
23,24,Dark Horse,Katy Perry,3.63,"February 20, 2014"
24,25,Perfect,Ed Sheeran,3.60,"November 9, 2017"
25,26,Let Her Go,Passenger,3.56,"July 25, 2012"
26,27,Faded,Alan Walker,3.55,"December 3, 2015"
27,28,Shree Hanuman Chalisa,T-Series Bhakti Sagar,3.54,"May 10, 2011"
28,29,Girls Like You,Maroon 5,3.52,"May 31, 2018"
29,30,Lean On,Major Lazer Official,3.50,"March 22, 2015"

# QUESTION 2

In [48]:
import time
driver = webdriver.Chrome()
#To load url
driver.get("https://www.bcci.tv/")
#To maximize window 
driver.maximize_window()
action = ActionChains(driver)

#to click fixtures
fixture_ele=driver.find_element(By.XPATH,"(//div[@class='imw-tabs international-tabs']/a[2])[1]")
fixture_ele.click()

#creating empty list for all attributes
series=[]
match=[]
place=[]
date=[]
times=[]

time.sleep(5)
more_matches=driver.find_element(By.XPATH,"/html/body/section/div/div/div/div/div/div[2]/div[2]/div[2]/div/button")
driver.execute_script("arguments[0].click();", more_matches)
time.sleep(5)
driver.execute_script("arguments[0].click();", more_matches)
time.sleep(5)
driver.execute_script("arguments[0].click();", more_matches)
  
time.sleep(5)
series_ele=driver.find_elements(By.XPATH,"//div[@class='match-card match-card-fw match-card-up ng-scope']/div/div/div/h5")
for i in series_ele:
    x=i.text
    series.append(x)
    
match_ele=driver.find_elements(By.XPATH,"//div[@class='match-card match-card-fw match-card-up ng-scope']/div/div/div/div/span[1]")
for i in match_ele:
    x=i.text
    match.append(x)
    
place_ele=driver.find_elements(By.XPATH,"//div[@class='match-card match-card-fw match-card-up ng-scope']/div[2]/div[1]")
for i in place_ele:
    x=i.text
    place.append(x)
    
date_ele=driver.find_elements(By.XPATH,"//div[@class='match-card match-card-fw match-card-up ng-scope']/div/div/div/div[2]/div[1]")
for i in date_ele:
    x=i.text
    date.append(x)
    
times_ele=driver.find_elements(By.XPATH,"//div[@class='match-card match-card-fw match-card-up ng-scope']/div/div/div/div[2]/div[2]")
for i in times_ele:
    x=i.text
    times.append(x)

print(series)
print(match)
print(place)
print(date)
print(times)

['ENGLAND A WOMENS TOUR OF INDIA T20 SERIES', 'AUSTRALIA TOUR OF INDIA 2023-24', 'ENGLAND A WOMENS TOUR OF INDIA T20 SERIES', 'AUSTRALIA TOUR OF INDIA 2023-24', 'ENGLAND WOMEN TOUR OF INDIA 2023-24', 'ENGLAND WOMEN TOUR OF INDIA 2023-24', 'ENGLAND WOMEN TOUR OF INDIA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'ENGLAND WOMEN TOUR OF INDIA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24', 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24', 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24', 'INDIA TOUR OF SOUTH AFRICA 2023-24', 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24', 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24', 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24', 'AFGHANISTAN TOUR OF INDIA 2023-24', 'AFGHANISTAN TOUR OF INDIA 2023-24', 'AFGHANISTAN TOUR OF INDIA 2023-24', 'ENGLAND TOUR OF INDIA 2023-24', 'ENGLAND TOUR OF INDIA 2023-24', 'ENGLAND TOUR OF INDIA 2023-24', 'ENGLAND TOUR OF INDIA 2023-24', 'ENGLAND TOUR OF INDIA 2023-24']
["Women's T20 Match", '4th T20I', "Women's T20 Match", '5th T20I', '1st T20I', '2nd T20I', '3rd T20I', '1st T20I', '2nd T20I', '1st Test', '3rd T20I', '1st ODI', '2nd ODI', '1st Test', '3rd ODI', '1st Test', '1st ODI', '2nd ODI', '3rd ODI', '2nd Test', '1st T20I', '2nd T20I', '3rd T20I', '1st T20I', '2nd T20I', '3rd T20I', '1st Test', '2nd Test', '3rd Test', '4th Test', '5th Test']
['Wankhede Stadium, Mumbai', 'Shaheed Veer Narayan Singh International Cricket Stadium, Raipur', 'Wankhede Stadium, Mumbai', 'M Chinnaswamy Stadium, Bengaluru', 'Wankhede Stadium, Mumbai', 'Wankhede Stadium, Mumbai', 'Wankhede Stadium, Mumbai', 'Kingsmead, Durban', "St George's Park, Gqeberha", 'DY Patil Stadium, NAVI MUMBAI', 'The Wanderers Stadium, Johannesburg', 'Johannesburg', "St George's Park, Gqeberha", 'Wankhede Stadium, Mumbai', 'Boland Park, Paarl', 'SuperSport Park, Centurion', 'Wankhede Stadium, Mumbai', 'Wankhede Stadium, Mumbai', 'Wankhede Stadium, Mumbai', 'Newlands, Cape Town', 'DY Patil Stadium, NAVI MUMBAI', 'DY Patil Stadium, NAVI MUMBAI', 'DY Patil Stadium, NAVI MUMBAI', 'Punjab Cricket Association IS Bindra Stadium, Mohali', 'Holkar Cricket Stadium, Indore', 'M Chinnaswamy Stadium, Bengaluru', 'Rajiv Gandhi International Stadium, Hyderabad', 'Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam', 'Saurashtra Cricket Association Stadium, Rajkot', 'JSCA International Stadium Complex, Ranchi', 'Himachal Pradesh Cricket Association Stadium, Dharamsala']
['1 DECEMBER, 2023', '1 DECEMBER, 2023', '3 DECEMBER, 2023', '3 DECEMBER, 2023', '6 DECEMBER, 2023', '9 DECEMBER, 2023', '10 DECEMBER, 2023', '10 DECEMBER, 2023', '12 DECEMBER, 2023', '14 DECEMBER, 2023', '14 DECEMBER, 2023', '17 DECEMBER, 2023', '19 DECEMBER, 2023', '21 DECEMBER, 2023', '21 DECEMBER, 2023', '26 DECEMBER, 2023', '28 DECEMBER, 2023', '30 DECEMBER, 2023', '2 JANUARY, 2024', '3 JANUARY, 2024', '5 JANUARY, 2024', '7 JANUARY, 2024', '9 JANUARY, 2024', '11 JANUARY, 2024', '14 JANUARY, 2024', '17 JANUARY, 2024', '25 JANUARY, 2024', '2 FEBRUARY, 2024', '15 FEBRUARY, 2024', '23 FEBRUARY, 2024', '7 MARCH, 2024']
['1:30 PM IST', '7:00 PM IST', '1:30 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '9:30 PM IST', '9:30 PM IST', '9:30 AM IST', '9:30 PM IST', '2:00 PM IST', '2:00 PM IST', '9:30 AM IST', '2:00 PM IST', '1:30 PM IST', '2:00 PM IST', '2:00 PM IST', '2:00 PM IST', '1:30 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '9:30 AM IST', '9:30 AM IST', '9:30 AM IST', '9:30 AM IST', '9:30 AM IST']

In [49]:
print(len(series),len(match),len(place),len(date),len(times))

31 31 31 31 31

In [50]:
df = pd.DataFrame({'SERIES': series, 'MATCH INFO': match, 'PLACE': place, 'DATE': date, 'TIME': times})
df

,SERIES,MATCH INFO,PLACE,DATE,TIME
0,ENGLAND A WOMENS TOUR OF INDIA T20 SERIES,Women's T20 Match,"Wankhede Stadium, Mumbai","1 DECEMBER, 2023",1:30 PM IST
1,AUSTRALIA TOUR OF INDIA 2023-24,4th T20I,Shaheed Veer Narayan Singh International Crick...,"1 DECEMBER, 2023",7:00 PM IST
2,ENGLAND A WOMENS TOUR OF INDIA T20 SERIES,Women's T20 Match,"Wankhede Stadium, Mumbai","3 DECEMBER, 2023",1:30 PM IST
3,AUSTRALIA TOUR OF INDIA 2023-24,5th T20I,"M Chinnaswamy Stadium, Bengaluru","3 DECEMBER, 2023",7:00 PM IST
4,ENGLAND WOMEN TOUR OF INDIA 2023-24,1st T20I,"Wankhede Stadium, Mumbai","6 DECEMBER, 2023",7:00 PM IST
5,ENGLAND WOMEN TOUR OF INDIA 2023-24,2nd T20I,"Wankhede Stadium, Mumbai","9 DECEMBER, 2023",7:00 PM IST
6,ENGLAND WOMEN TOUR OF INDIA 2023-24,3rd T20I,"Wankhede Stadium, Mumbai","10 DECEMBER, 2023",7:00 PM IST
7,INDIA TOUR OF SOUTH AFRICA 2023-24,1st T20I,"Kingsmead, Durban","10 DECEMBER, 2023",9:30 PM IST
8,INDIA TOUR OF SOUTH AFRICA 2023-24,2nd T20I,"St George's Park, Gqeberha","12 DECEMBER, 2023",9:30 PM IST
9,ENGLAND WOMEN TOUR OF INDIA 2023-24,1st Test,"DY Patil Stadium, NAVI MUMBAI","14 DECEMBER, 2023",9:30 AM IST
10,INDIA TOUR OF SOUTH AFRICA 2023-24,3rd T20I,"The Wanderers Stadium, Johannesburg","14 DECEMBER, 2023",9:30 PM IST
11,INDIA TOUR OF SOUTH AFRICA 2023-24,1st ODI,Johannesburg,"17 DECEMBER, 2023",2:00 PM IST
12,INDIA TOUR OF SOUTH AFRICA 2023-24,2nd ODI,"St George's Park, Gqeberha","19 DECEMBER, 2023",2:00 PM IST
13,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,1st Test,"Wankhede Stadium, Mumbai","21 DECEMBER, 2023",9:30 AM IST
14,INDIA TOUR OF SOUTH AFRICA 2023-24,3rd ODI,"Boland Park, Paarl","21 DECEMBER, 2023",2:00 PM IST
15,INDIA TOUR OF SOUTH AFRICA 2023-24,1st Test,"SuperSport Park, Centurion","26 DECEMBER, 2023",1:30 PM IST
16,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,1st ODI,"Wankhede Stadium, Mumbai","28 DECEMBER, 2023",2:00 PM IST
17,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,2nd ODI,"Wankhede Stadium, Mumbai","30 DECEMBER, 2023",2:00 PM IST
18,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,3rd ODI,"Wankhede Stadium, Mumbai","2 JANUARY, 2024",2:00 PM IST
19,INDIA TOUR OF SOUTH AFRICA 2023-24,2nd Test,"Newlands, Cape Town","3 JANUARY, 2024",1:30 PM IST
20,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,1st T20I,"DY Patil Stadium, NAVI MUMBAI","5 JANUARY, 2024",7:00 PM IST
21,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,2nd T20I,"DY Patil Stadium, NAVI MUMBAI","7 JANUARY, 2024",7:00 PM IST
22,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,3rd T20I,"DY Patil Stadium, NAVI MUMBAI","9 JANUARY, 2024",7:00 PM IST
23,AFGHANISTAN TOUR OF INDIA 2023-24,1st T20I,"Punjab Cricket Association IS Bindra Stadium, ...","11 JANUARY, 2024",7:00 PM IST
24,AFGHANISTAN TOUR OF INDIA 2023-24,2nd T20I,"Holkar Cricket Stadium, Indore","14 JANUARY, 2024",7:00 PM IST
25,AFGHANISTAN TOUR OF INDIA 2023-24,3rd T20I,"M Chinnaswamy Stadium, Bengaluru","17 JANUARY, 2024",7:00 PM IST
26,ENGLAND TOUR OF INDIA 2023-24,1st Test,"Rajiv Gandhi International Stadium, Hyderabad","25 JANUARY, 2024",9:30 AM IST
27,ENGLAND TOUR OF INDIA 2023-24,2nd Test,Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadi...,"2 FEBRUARY, 2024",9:30 AM IST
28,ENGLAND TOUR OF INDIA 2023-24,3rd Test,"Saurashtra Cricket Association Stadium, Rajkot","15 FEBRUARY, 2024",9:30 AM IST
29,ENGLAND TOUR OF INDIA 2023-24,4th Test,"JSCA International Stadium Complex, Ranchi","23 FEBRUARY, 2024",9:30 AM IST
30,ENGLAND TOUR OF INDIA 2023-24,5th Test,"Himachal Pradesh Cricket Association Stadium, ...","7 MARCH, 2024",9:30 AM IST

# QUESTION 3

In [40]:
driver = webdriver.Chrome()
#To load url
driver.get("https://statisticstimes.com/")
#To maximize window 
driver.maximize_window()

#to click economy
economy_ele=driver.find_element(By.XPATH,"//div[@class ='navbar']/div[2]/button")
economy_ele.click()

#to click India
time.sleep(2)
India_ele=driver.find_element(By.XPATH,"//div[@class ='navbar']/div[2]/div/a[3]")
India_ele.click()

#to click  GDP of Indian states
time.sleep(10)
gdp_ele=driver.find_element(By.XPATH,"//ul[@style='list-style-type:none;margin-left:20px;']/li[1]/a")
gdp_ele.click()

#creating empty list for all attributes
rank=[]
state=[]
gsdp_19_20=[]
gsdp_18_19=[]
share=[]
gdp=[]

time.sleep(5)
rank_ele=driver.find_elements(By.XPATH,"(//table[@class='display dataTable'])[1]/tbody/tr/td[1]")
for i in rank_ele:
    x=i.text
    rank.append(x)

state_ele=driver.find_elements(By.XPATH,"(//table[@class='display dataTable'])[1]/tbody/tr/td[2]")
for i in state_ele:
    x=i.text
    state.append(x)

gsdp_19_20_ele=driver.find_elements(By.XPATH,"(//table[@class='display dataTable'])[1]/tbody/tr/td[3]")
for i in gsdp_19_20_ele:
    x=i.text
    gsdp_19_20.append(x)
    
gsdp_18_19_ele=driver.find_elements(By.XPATH,"(//table[@class='display dataTable'])[1]/tbody/tr/td[4]")
for i in gsdp_18_19_ele:
    x=i.text
    gsdp_18_19.append(x)
    
share_ele=driver.find_elements(By.XPATH,"(//table[@class='display dataTable'])[1]/tbody/tr/td[5]")
for i in share_ele:
    x=i.text
    share.append(x)
    
gdp_ele=driver.find_elements(By.XPATH,"(//table[@class='display dataTable'])[1]/tbody/tr/td[6]")
for i in gdp_ele:
    x=i.text
    gdp.append(x)
        
print(rank)
print(state)
print(gsdp_19_20)
print(gsdp_18_19)
print(share)
print(gdp)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']
['Maharashtra', 'Tamil Nadu', 'Uttar Pradesh', 'Gujarat', 'Karnataka', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Punjab', 'Odisha', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Nagaland', 'Arunachal Pradesh', 'Mizoram', 'Andaman & Nicobar Islands']
['-', '1,845,853', '1,687,818', '-', '1,631,977', '1,253,832', '1,020,989', '972,782', '969,604', '906,672', '-', '856,112', '831,610', '611,804', '574,760', '521,275', '-', '329,180', '328,598', '-', '-', '165,472', '80,449', '55,984', '-', '38,253', '36,572', '32,496', '31,790', '-', '-', '26,503', '-']
['2,632,792', '1,630,208', '1,584,764', '1,502,899', '1,493,127', '1,089,898', '942,586', '862,957', '861,031', '809,592', '781,653', '774,870', '734,163', '530,363', '526,376', '487,805', '315,881', '304,063', '297,204', '245,895', '155,956', '153,845', '73,170', '49,845', '42,114', '34,433', '33,481', '28,723', '27,870', '27,283', '24,603', '22,287', '-']
['13.94%', '8.63%', '8.39%', '7.96%', '7.91%', '5.77%', '4.99%', '4.57%', '4.56%', '4.29%', '4.14%', '4.10%', '3.89%', '2.81%', '2.79%', '2.58%', '1.67%', '1.61%', '1.57%', '1.30%', '0.83%', '0.81%', '0.39%', '0.26%', '0.22%', '0.18%', '0.18%', '0.15%', '0.15%', '0.14%', '0.13%', '0.12%', '-']
['399.921', '247.629', '240.726', '228.290', '226.806', '165.556', '143.179', '131.083', '130.791', '122.977', '118.733', '117.703', '111.519', '80.562', '79.957', '74.098', '47.982', '46.187', '45.145', '37.351', '23.690', '23.369', '11.115', '7.571', '6.397', '5.230', '5.086', '4.363', '4.233', '4.144', '3.737', '3.385', '-']

In [41]:
print(len(rank),len(state),len(gsdp_19_20),len(gsdp_18_19),len(share),len(gdp))

33 33 33 33 33 33

In [42]:
df = pd.DataFrame({'RANK': rank, 'STATE': state, 'GSDP(19-20)- at current prices': gsdp_19_20, 'GSDP(18-19)- at current prices': gsdp_18_19, 'Share(18-19)': share, 'GDP($ billion)': gdp})
df

,RANK,STATE,GSDP(19-20)- at current prices,GSDP(18-19)- at current prices,Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# QUESTION 4

In [51]:
driver = webdriver.Chrome()
#To load url
driver.get("https://github.com")
#To maximize window 
driver.maximize_window()

open_source_ele=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
open_source_ele.click()

time.sleep(5)
trending_ele=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a")
trending_ele.click()

#creating empty list for all attributes
title=[]
desc=[]
count=[]
lang=[]

time.sleep(5)
title_ele=driver.find_elements(By.XPATH,"//article[@class='Box-row']/h2/a")
for i in title_ele:
    x=i.text
    title.append(x)
    
    
count_ele=driver.find_elements(By.XPATH,"//article[@class='Box-row']/div[2]/a[2]")
for i in count_ele:
    x=i.text
    count.append(x)
    
all_repos=driver.find_elements(By.XPATH,"//article[@class='Box-row']")
for repo in all_repos:
    time.sleep(2)
    try:
        if len(repo.find_elements(By.XPATH,".//span[@itemprop='programmingLanguage']"))>0:
            lang_ele=repo.find_elements(By.XPATH,".//span[@itemprop='programmingLanguage']")
            for i in lang_ele:
                x=i.text
                lang.append(x)
        else:
            lang.append('-')
    except:
        pass
    
    try:
        if len(repo.find_elements(By.XPATH,".//p[@class='col-9 color-fg-muted my-1 pr-4']"))>0:
            desc_ele=repo.find_elements(By.XPATH,".//p[@class='col-9 color-fg-muted my-1 pr-4']")
            for i in desc_ele:
                x=i.text
                desc.append(x)
        else:
            desc.append('-')
    except:
        pass

print(title)
print(desc)
print(count)
print(lang)

['LouisShark / chatgpt_system_prompt', 'federico-busato / Modern-CPP-Programming', 'nlohmann / json', 'epfLLM / meditron', 'comfyanonymous / ComfyUI', 'openai / openai-python', 'grpc-ecosystem / grpc-gateway', 'linexjlin / GPTs', 'mlabonne / llm-course', 'kamranahmedse / developer-roadmap', 'makeplane / plane', 'StanGirard / quivr', 'lllyasviel / Fooocus', 'straight-tamago / misaka', 'roboflow / multimodal-maestro', 'pointfreeco / swift-composable-architecture', 'opa334 / TrollStore', '521xueweihan / HelloGitHub', 'openai / openai-cookbook', 'fastlane / fastlane', 'Vaibhavs10 / insanely-fast-whisper', 'Ftindy / IPTV-URL', 'danswer-ai / danswer', 'SamurAIGPT / Open-Custom-GPT', 'ascoders / weekly']
["store all agent's system prompt", 'Modern C++ Programming Course (C++11/14/17/20)', 'JSON for Modern C++', 'Meditron is a suite of open-source medical Large Language Models (LLMs).', 'The most powerful and modular stable diffusion GUI with a graph/nodes interface.', 'The official Python library for the OpenAI API', 'gRPC to JSON proxy generator following the gRPC HTTP spec', 'leaked prompts of GPTs', 'Course to get into Large Language Models (LLMs) with roadmaps and Colab notebooks.', 'Interactive roadmaps, guides and other educational content to help developers grow in their careers.', '🔥 🔥 🔥 Open Source JIRA, Linear and Height Alternative. Plane helps you track your issues, epics, and product roadmaps in the simplest way possible.', 'Your GenAI Second Brain 🧠 A personal productivity assistant ⚡️🤖 Chat with your files (PDF, CSV, ...) & apps using GPT 3.5 / 4 turbo, Private, Anthropic, VertexAI, Ollama, LLMs, that you can share with users ! Local & Private alternative to OpenAI GPTs.', 'Focus on prompting and generating', '-', 'Effective prompting for Large Multimodal Models like GPT-4 Vision or LLaVA. 🔥', 'A library for building applications in a consistent and understandable way, with composition, testing, and ergonomics in mind.', 'Jailed iOS app that can install IPAs permanently with arbitary entitlements and root helpers because it trolls Apple', '分享 GitHub 上有趣、入门级的开源项目。Share interesting, entry-level open source projects on GitHub.', 'Examples and guides for using the OpenAI API', '🚀 The easiest way to automate building and releasing your iOS and Android apps', '-', '-', 'Ask Questions in natural language and get Answers backed by private sources. Connects to tools like Slack, GitHub, Confluence, etc.', 'Create Custom GPT and add/embed on your site using Assistants api', '前端精读周刊。帮你理解最前沿、实用的技术。']
['756', '359', '6,457', '28', '1,635', '2,146', '2,151', '1,230', '194', '35,673', '894', '2,736', '1,621', '22', '31', '1,152', '842', '9,487', '8,462', '5,704', '262', '190', '447', '112', '3,028']
['C', '-', 'C++', 'Python', 'Python', 'Python', 'Go', '-', 'Jupyter Notebook', 'TypeScript', 'TypeScript', 'TypeScript', 'Python', 'CSS', 'Python', 'Swift', 'C', 'Python', 'MDX', 'Ruby', 'Jupyter Notebook', '-', 'Python', 'JavaScript', 'JavaScript']

In [52]:
print(len(title),len(count),len(lang),len(desc))

25 25 25 25

In [53]:
df = pd.DataFrame({'Repository title': title, 'Repository description': desc, 'Contributors Count': count, 'Language used': lang})
df

,Repository title,Repository description,Contributors Count,Language used
0,LouisShark / chatgpt_system_prompt,store all agent's system prompt,756,C
1,federico-busato / Modern-CPP-Programming,Modern C++ Programming Course (C++11/14/17/20),359,-
2,nlohmann / json,JSON for Modern C++,"6,457",C++
3,epfLLM / meditron,Meditron is a suite of open-source medical Lar...,28,Python
4,comfyanonymous / ComfyUI,The most powerful and modular stable diffusion...,"1,635",Python
5,openai / openai-python,The official Python library for the OpenAI API,"2,146",Python
6,grpc-ecosystem / grpc-gateway,gRPC to JSON proxy generator following the gRP...,"2,151",Go
7,linexjlin / GPTs,leaked prompts of GPTs,"1,230",-
8,mlabonne / llm-course,Course to get into Large Language Models (LLMs...,194,Jupyter Notebook
9,kamranahmedse / developer-roadmap,"Interactive roadmaps, guides and other educati...","35,673",TypeScript
10,makeplane / plane,"🔥 🔥 🔥 Open Source JIRA, Linear and Height Alte...",894,TypeScript
11,StanGirard / quivr,Your GenAI Second Brain 🧠 A personal productiv...,"2,736",TypeScript
12,lllyasviel / Fooocus,Focus on prompting and generating,"1,621",Python
13,straight-tamago / misaka,-,22,CSS
14,roboflow / multimodal-maestro,Effective prompting for Large Multimodal Model...,31,Python
15,pointfreeco / swift-composable-architecture,A library for building applications in a consi...,"1,152",Swift
16,opa334 / TrollStore,Jailed iOS app that can install IPAs permanent...,842,C
17,521xueweihan / HelloGitHub,"分享 GitHub 上有趣、入门级的开源项目。Share interesting, entr...","9,487",Python
18,openai / openai-cookbook,Examples and guides for using the OpenAI API,"8,462",MDX
19,fastlane / fastlane,🚀 The easiest way to automate building and rel...,"5,704",Ruby
20,Vaibhavs10 / insanely-fast-whisper,-,262,Jupyter Notebook
21,Ftindy / IPTV-URL,-,190,-
22,danswer-ai / danswer,Ask Questions in natural language and get Answ...,447,Python
23,SamurAIGPT / Open-Custom-GPT,Create Custom GPT and add/embed on your site u...,112,JavaScript
24,ascoders / weekly,前端精读周刊。帮你理解最前沿、实用的技术。,"3,028",JavaScript

# QUESTION 5

In [5]:
driver = webdriver.Chrome()
#To load url
driver.get("https://www.billboard.com/")
#To maximize window 
driver.maximize_window()

time.sleep(5)
btn_clk=driver.find_element(By.XPATH,"(//button[@class='o-icon-button lrv-a-unstyle-button lrv-a-unstyle-link lrv-u-cursor-pointer lrv-u-flex js-MegaMenu-Trigger lrv-u-color-grey:hover lrv-a-hover-effect'])[1]")
btn_clk.click()

time.sleep(3)
bill_100=driver.find_element(By.XPATH,"/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a")
bill_100.click()

#creating empty list for all attributes
rank=[]
song=[]
artist=[]
last_week=[]
peak=[]
total_weeks=[]

time.sleep(5)
rank_ele=driver.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']/ul/li[1]/span[1]")
for i in rank_ele:
    x=i.text
    rank.append(x)

song_ele=driver.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']/ul/li[4]/ul/li/h3")
for i in song_ele:
    x=i.text
    song.append(x)
    
artist_ele=driver.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']/ul/li[4]/ul/li[1]/span")
for i in artist_ele:
    x=i.text
    artist.append(x)
    
last_week_ele=driver.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']/ul/li[4]/ul/li[4]/span")
for i in last_week_ele:
    x=i.text
    last_week.append(x)
    
peak_ele=driver.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']/ul/li[4]/ul/li[5]/span")
for i in peak_ele:
    x=i.text
    peak.append(x)
    
total_weeks_ele=driver.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']/ul/li[4]/ul/li[6]/span")
for i in total_weeks_ele:
    x=i.text
    total_weeks.append(x)
    
print(rank)
print(song)
print(artist)
print(last_week)
print(peak)
print(total_weeks)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100']
['Lovin On Me', 'Cruel Summer', 'Paint The Town Red', 'All I Want For Christmas Is You', 'Snooze', 'I Remember Everything', 'Greedy', "Rockin' Around The Christmas Tree", "Is It Over Now? (Taylor's Version) [From The Vault]", 'Water', 'You Broke My Heart', 'Jingle Bell Rock', 'Last Christmas', 'Last Night', "Thinkin' Bout Me", 'A Holly Jolly Christmas', 'First Person Shooter', 'Fast Car', 'Agora Hills', 'Rich Baby Daddy', 'Need A Favor', 'Save Me', 'Vampire', 'Lil Boo Thang', 'Fukumean', 'Evil Ways', 'White Horse', "It's The Most Wonderful Time Of The Year", 'IDGAF', 'Used To Be Young', 'Dance The Night', 'Good Good', 'Houdini', 'Exes', 'Let It Snow, Let It Snow, Let It Snow!', 'What Was I Made For?', 'Stick Season', 'Monaco', 'Feliz Navidad', 'Lose Control', 'Dial Drunk', 'Underneath The Tree', 'The Christmas Song (Merry Christmas To You)', 'My Love Mine All Mine', 'What It Is (Block Boy)', 'Sleigh Ride', 'Flowers', 'Santa Tell Me', 'Kill Bill', 'Virginia Beach', 'Red Button', 'The Shoe Fits', 'Pretty Little Poison', 'I Know ?', 'World On Fire', "Now That We Don't Talk (Taylor's Version) [From The Vault]", 'Harley Quinn', 'Stories About My Brother', 'On My Mama', 'Wild Ones', "Can't Have Mine", '500lbs', "Can't Catch Me Now", 'Strangers', 'Great Gatsby', 'Truck Bed', 'Get Him Back!', 'Try That In A Small Town', 'Everything I Love', 'The Painter', 'Wick Man', 'Qlona', 'Standing Next To You', 'Slime You Out', 'Bad Idea Right?', "Slut! (Taylor's Version) [From The Vault]", 'Hey Driver', 'Segun Quien', 'Northern Attitude', 'Burn It Down', "Say Don't Go (Taylor's Version) [From The Vault]", 'Perro Negro', 'Que Onda', 'Where The Wild Things Are', 'Rich Men North Of Richmond', 'Turks & Caicos', 'Save Me The Trouble', 'SkeeYee', 'LaLa', 'I Swear, I Really Wanted To Make A "Rap" Album But...', "Style (Taylor's Version)", 'El Amor de Su Vida', 'Too Much', 'Meltdown', 'Surround Sound', "Different 'Round Here", 'Bongos', 'But I Got A Beer In My Hand', 'Calling For You', 'Mi Ex Tenia Razon']
['Jack Harlow', 'Taylor Swift', 'Doja Cat', 'Mariah Carey', 'SZA', 'Zach Bryan Featuring Kacey Musgraves', 'Tate McRae', 'Brenda Lee', 'Taylor Swift', 'Tyla', 'Drake', 'Bobby Helms', 'Wham!', 'Morgan Wallen', 'Morgan Wallen', 'Burl Ives', 'Drake Featuring J. Cole', 'Luke Combs', 'Doja Cat', 'Drake Featuring Sexyy Red & SZA', 'Jelly Roll', 'Jelly Roll With Lainey Wilson', 'Olivia Rodrigo', 'Paul Russell', 'Gunna', 'Drake Featuring J. Cole', 'Chris Stapleton', 'Andy Williams', 'Drake Featuring Yeat', 'Miley Cyrus', 'Dua Lipa', 'Usher, Summer Walker & 21 Savage', 'Dua Lipa', 'Tate McRae', 'Dean Martin', 'Billie Eilish', 'Noah Kahan', 'Bad Bunny', 'Jose Feliciano', 'Teddy Swims', 'Noah Kahan With Post Malone', 'Kelly Clarkson', 'Nat King Cole', 'Mitski', 'Doechii Featuring Kodak Black', 'The Ronettes', 'Miley Cyrus', 'Ariana Grande', 'SZA', 'Drake', 'Drake', 'Drake', 'Warren Zeiders', 'Travis Scott', 'Nate Smith', 'Taylor Swift', 'Fuerza Regida & Marshmello', 'Drake', 'Victoria Monet', 'Jessie Murph & Jelly Roll', 'Dylan Scott', 'Lil Tecca', 'Olivia Rodrigo', 'Kenya Grace', 'Rod Wave', 'HARDY', 'Olivia Rodrigo', 'Jason Aldean', 'Morgan Wallen', 'Cody Johnson', 'Drake', 'Karol G & Peso Pluma', 'Jung Kook', 'Drake Featuring SZA', 'Olivia Rodrigo', 'Taylor Swift', 'Zach Bryan Featuring The War And Treaty', 'Maluma & Carin Leon', 'Noah Kahan With Hozier', 'Parker McCollum', 'Taylor Swift', 'Bad Bunny & Feid', 'Calle 24 x Chino Pacas x Fuerza Regida', 'Luke Combs', 'Oliver Anthony Music', 'Rod Wave Featuring 21 Savage', 'Dan + Shay', 'Sexyy Red', 'Myke Towers', 'Andre 3000', 'Taylor Swift', 'Grupo Frontera & Grupo Firme', 'The Kid LAROI, Jung Kook & Central Cee', 'Travis Scott Featuring Drake', 'JID Featuring 21 Savage & Baby Tate', 'Riley Green Featuring Luke Combs', 'Cardi B & Megan Thee Stallion', 'Luke Bryan', 'Drake Featuring 21 Savage', 'Karol G']
['2', '1', '3', '17', '4', '6', '8', '-', '5', '15', '-', '38', '32', '9', '10', '44', '25', '7', '14', '16', '13', '19', '21', '23', '18', '-', '12', '-', '26', '22', '20', '28', '11', '-', '-', '27', '31', '24', '-', '39', '34', '-', '-', '30', '35', '-', '29', '-', '36', '58', '-', '-', '46', '42', '47', '33', '40', '-', '48', '43', '57', '51', '81', '52', '55', '64', '56', '61', '59', '62', '-', '65', '50', '73', '54', '49', '68', '74', '37', '78', '53', '67', '75', '-', '70', '82', '88', '83', '79', '-', '69', '87', '66', '71', '-', '97', '72', '98', '-', '96']
['1', '1', '1', '1', '2', '1', '7', '2', '1', '10', '11', '3', '4', '1', '7', '4', '1', '2', '14', '11', '13', '19', '1', '23', '4', '26', '12', '5', '2', '8', '6', '25', '11', '34', '8', '14', '31', '5', '6', '39', '25', '12', '9', '26', '29', '10', '1', '12', '1', '3', '51', '52', '46', '11', '47', '2', '40', '58', '48', '42', '57', '51', '56', '52', '30', '55', '11', '1', '14', '55', '71', '28', '5', '1', '7', '3', '14', '68', '37', '77', '5', '20', '61', '84', '1', '24', '84', '62', '43', '90', '9', '68', '44', '3', '90', '96', '14', '92', '5', '22']
['2', '29', '16', '60', '50', '13', '10', '53', '4', '8', '1', '51', '33', '43', '38', '34', '7', '35', '9', '7', '34', '23', '21', '10', '23', '1', '18', '34', '7', '13', '26', '15', '2', '1', '26', '19', '8', '6', '27', '15', '23', '22', '39', '9', '29', '23', '45', '19', '50', '7', '1', '1', '11', '17', '4', '4', '3', '1', '10', '7', '8', '9', '3', '10', '10', '23', '11', '19', '39', '7', '1', '15', '3', '10', '15', '4', '13', '8', '2', '5', '4', '6', '8', '1', '15', '10', '4', '12', '20', '1', '4', '13', '5', '17', '2', '2', '11', '6', '4', '14']

In [6]:
print(len(rank),len(song),len(artist),len(last_week),len(peak),len(total_weeks))

100 100 100 100 100 100

In [7]:
df = pd.DataFrame({'RANK': rank, 'SONG NAME': song, 'ARTIST NAME': artist, 'LAST WEEK RANK': last_week, 'PEAK RANK': peak, 'WEEKS ON CHART': total_weeks})
df

,RANK,SONG NAME,ARTIST NAME,LAST WEEK RANK,PEAK RANK,WEEKS ON CHART
0,1,Lovin On Me,Jack Harlow,2,1,2
1,2,Cruel Summer,Taylor Swift,1,1,29
2,3,Paint The Town Red,Doja Cat,3,1,16
3,4,All I Want For Christmas Is You,Mariah Carey,17,1,60
4,5,Snooze,SZA,4,2,50
...,...,...,...,...,...,...
95,96,Different 'Round Here,Riley Green Featuring Luke Combs,97,96,2
96,97,Bongos,Cardi B & Megan Thee Stallion,72,14,11
97,98,But I Got A Beer In My Hand,Luke Bryan,98,92,6
98,99,Calling For You,Drake Featuring 21 Savage,-,5,4
99,100,Mi Ex Tenia Razon,Karol G,96,22,14

# QUESTION 6

In [11]:
driver = webdriver.Chrome()
#To load url
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
#To maximize window 
driver.maximize_window()

#creating empty list for all attributes
rank=[]
book=[]
author=[]
sold=[]
publisher=[]
genre=[]

time.sleep(5)
rank_ele=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[1]")
for i in rank_ele:
    x=i.text
    rank.append(x)
    
book_ele=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[2]")
for i in book_ele:
    x=i.text
    book.append(x)
    
author_ele=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[3]")
for i in author_ele:
    x=i.text
    author.append(x)
    
sold_ele=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[4]")
for i in sold_ele:
    x=i.text
    sold.append(x)
    
publisher_ele=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[5]")
for i in publisher_ele:
    x=i.text
    publisher.append(x)
    
genre_ele=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[6]")
for i in genre_ele:
    x=i.text
    genre.append(x)
    
print(rank)
print(book)
print(author)
print(sold)
print(publisher)
print(genre)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100']
['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]
['Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie']
['5,094,805', '4,475,152', '4,200,654', '4,179,479', '3,758,936', '3,583,215', '3,484,047', '3,377,906', '3,193,946', '2,950,264', '2,479,784', '2,315,405', '2,233,570', '2,193,928', '2,183,031', '2,152,737', '2,062,145', '2,052,876', '2,005,598', '1,979,552', '1,928,900', '1,852,919', '1,814,784', '1,787,118', '1,783,535', '1,781,269', '1,743,266', '1,629,119', '1,616,068', '1,583,992', '1,555,135', '1,546,886', '1,539,428', '1,508,205', '1,489,403', '1,352,318', '1,310,207', '1,310,176', '1,231,957', '1,217,712', '1,208,711', '1,204,058', '1,184,967', '1,181,503', '1,181,093', '1,153,181', '1,132,336', '1,130,802', '1,126,337', '1,115,549', '1,108,328', '1,107,379', '1,104,403', '1,092,349', '1,090,847', '1,087,262', '1,054,196', '1,037,160', '1,023,688', '1,015,956', '1,009,873', '1,004,414', '1,003,780', '1,002,314', '998,213', '992,846', '986,753', '986,115', '970,509', '967,466', '963,353', '962,515', '959,496', '956,114', '945,640', '931,312', '925,425', '924,695', '906,968', '905,086', '890,847', '869,671', '869,659', '862,602', '856,540', '845,858', '842,535', '828,215', '820,563', '816,907', '816,585', '815,586', '814,370', '809,641', '808,900', '807,311', '794,201', '792,187', '791,507', '791,095']
['Transworld', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Random House', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Transworld', 'Bloomsbury', 'Random House', 'Little, Brown Book', 'Quercus', 'Random House', 'Transworld', 'Little, Brown Book', 'Transworld', 'Little, Brown Book', 'Pan Macmillan', 'Random House', 'Transworld', 'Transworld', 'Quercus', 'Little, Brown Book', 'Penguin', 'Pan Macmillan', 'Penguin', 'Bloomsbury', 'Hodder & Stoughton', 'Bloomsbury', 'Quercus', 'Random House', 'Random House', 'Pan Macmillan', 'Penguin', 'Random House', 'Random House', 'Canongate', 'HarperCollins', 'Orion', 'Pan Macmillan', 'HarperCollins', 'Random House', 'Scholastic Ltd.', 'Orion', 'Bloomsbury', 'Penguin', 'HarperCollins', 'Random House', 'Little, Brown Book', 'Headline', 'HarperCollins', 'Penguin', 'Orion', 'Bloomsbury', 'Random House', 'Random House', 'Scholastic Ltd.', 'Profile Books Group', 'Random House', 'Transworld', 'Random House Childrens Books G', 'Hodder & Stoughton', 'Scholastic Ltd.', 'Random House', 'HarperCollins', 'Random House', 'Penguin', 'Random House', 'HarperCollins', 'Penguin', 'Headline', 'Little, Brown Book', 'HarperCollins', 'Transworld', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Transworld', 'Transworld', 'Random House', 'Headline', 'Random House', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Hodder & Stoughton', 'Transworld', 'D.C. Thomson', 'Penguin', 'Pan Macmillan', 'Transworld', 'Orion', 'Random House', 'Penguin', 'Scholastic Ltd.', 'Orion', 'Penguin']
['Crime, Thriller & Adventure', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Romance & Sagas', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Crime, Thriller & Adventure', "Children's Fiction", 'Romance & Sagas', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Romance & Sagas', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Popular Science', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Picture Books', 'Picture Books', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Humour: Collections & General', 'General & Literary Fiction', 'Autobiography: General', 'General & Literary Fiction', 'Biography: The Arts', 'Autobiography: General', 'Picture Books', 'Autobiography: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Science Fiction & Fantasy', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'Fitness & Diet', 'General & Literary Fiction', "Children's Fiction", 'Crime, Thriller & Adventure', 'Fitness & Diet', 'Young Adult Fiction', 'Usage & Writing Guides', 'Food & Drink: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Popular Culture & Media: General Interest', 'Autobiography: The Arts', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Science Fiction & Fantasy', 'Current Affairs & Issues', 'Crime, Thriller & Adventure', 'Autobiography: The Arts', 'General & Literary Fiction', 'Autobiography: The Arts', 'Travel Writing', 'Food & Drink: General', 'General & Literary Fiction', 'National & Regional Cuisine', 'Fitness & Diet', 'Travel Writing', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'Picture Books', 'General & Literary Fiction', 'Autobiography: The Arts', 'Popular Science', "Children's Annuals", 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Food & Drink: General', 'Young Adult Fiction', 'Biography: General', 'Food & Drink: General']

In [12]:
print(len(rank),len(book),len(author),len(sold),len(publisher),len(genre))

100 100 100 100 100 100

In [13]:
df = pd.DataFrame({'RANK': rank, 'BOOK NAME': book, 'AUTHOR NAME': author, 'VOLUMES SOLD': sold, 'PUBLISHER': publisher, 'GENRE': genre})
df

,RANK,BOOK NAME,AUTHOR NAME,VOLUMES SOLD,PUBLISHER,GENRE
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# QUESTION 7

In [18]:
driver = webdriver.Chrome()
#To load url
driver.get("https://www.imdb.com/list/ls095964455/")
#To maximize window 
driver.maximize_window()

#creating empty list for all attributes
rank=[]
show=[]
year=[]
run_time=[]
genre=[]
ratings=[]
votes=[]

time.sleep(5)
rank_ele=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/span[1]")
for i in rank_ele:
    x=i.text.replace('.','')
    rank.append(x)
    
show_ele=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/a")
for i in show_ele:
    x=i.text
    show.append(x)
    
year_ele=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/span[2]")
for i in year_ele:
    x=i.text
    year.append(x)
    
run_time_ele=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p[1]/span[3]")
for i in run_time_ele:
    x=i.text
    run_time.append(x)
    
genre_ele=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p[1]/span[5]")
for i in genre_ele:
    x=i.text
    genre.append(x)
    
ratings_ele=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/div[1]/div[1]/span[2]")
for i in ratings_ele:
    x=i.text
    ratings.append(x)
    
votes_ele=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p[4]/span[2]")
for i in votes_ele:
    x=i.text
    votes.append(x)
    
print(rank)
print(show)
print(year)
print(run_time)
print(genre)
print(ratings)
print(votes)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100']
['Game of Thrones', 'Stranger Things', 'The Walking Dead', '13 Reasons Why', 'The 100', 'Orange Is the New Black', 'Riverdale', "Grey's Anatomy", 'The Flash', 'Arrow', 'Money Heist', 'The Big Bang Theory', 'Black Mirror', 'Sherlock', 'Vikings', 'Pretty Little Liars', 'The Vampire Diaries', 'American Horror Story', 'Breaking Bad', 'Lucifer', 'Supernatural', 'Prison Break', 'How to Get Away with Murder', 'Teen Wolf', 'The Simpsons', 'Once Upon a Time', 'Narcos', 'Daredevil', 'Friends', 'How I Met Your Mother', 'Suits', 'Mr. Robot', 'The Originals', 'Supergirl', 'Gossip Girl', 'Sense8', 'Gotham', 'Westworld', 'Jessica Jones', 'Modern Family', 'Rick and Morty', 'Shadowhunters', 'The End of the F***ing World', 'House of Cards', 'Dark', 'Elite', 'Sex Education', 'Shameless', 'New Girl', 'Agents of S.H.I.E.L.D.', 'You', 'Dexter', 'Fear the Walking Dead', 'Family Guy', 'The Blacklist', 'Lost', 'Peaky Blinders', 'House', 'Quantico', 'Orphan Black', 'Homeland', 'Blindspot', "DC's Legends of Tomorrow", "The Handmaid's Tale", 'Chilling Adventures of Sabrina', 'The Good Doctor', 'Jane the Virgin', 'Glee', 'South Park', 'Brooklyn Nine-Nine', 'Under the Dome', 'The Umbrella Academy', 'True Detective', 'The OA', 'Desperate Housewives', 'Better Call Saul', 'Bates Motel', 'The Punisher', 'Atypical', 'Dynasty', 'This Is Us', 'The Good Place', 'Iron Fist', 'The Rain', 'Mindhunter', 'Revenge', 'Luke Cage', 'Scandal', 'The Defenders', 'Big Little Lies', 'Insatiable', 'The Mentalist', 'The Crown', 'Chernobyl', 'iZombie', 'Reign', 'A Series of Unfortunate Events', 'Criminal Minds', 'Scream: The TV Series', 'The Haunting of Hill House']
['(2011–2019)', '(2016–2025)', '(2010–2022)', '(2017–2020)', '(2014–2020)', '(2013–2019)', '(2017–2023)', '(2005– )', '(2014–2023)', '(2012–2020)', '(2017–2021)', '(2007–2019)', '(2011– )', '(2010–2017)', '(2013–2020)', '(2010–2017)', '(2009–2017)', '(2011– )', '(2008–2013)', '(2016–2021)', '(2005–2020)', '(2005–2017)', '(2014–2020)', '(2011–2017)', '(1989– )', '(2011–2018)', '(I) (2015–2017)', '(2015–2018)', '(1994–2004)', '(2005–2014)', '(2011–2019)', '(2015–2019)', '(2013–2018)', '(2015–2021)', '(2007–2012)', '(2015–2018)', '(2014–2019)', '(2016–2022)', '(2015–2019)', '(2009–2020)', '(2013– )', '(2016–2019)', '(2017–2019)', '(2013–2018)', '(2017–2020)', '(2018–2024)', '(2019–2023)', '(2011–2021)', '(2011–2018)', '(2013–2020)', '(2018–2024)', '(2006–2013)', '(2015–2023)', '(1999– )', '(2013–2023)', '(2004–2010)', '(2013–2022)', '(2004–2012)', '(2015–2018)', '(2013–2017)', '(2011–2020)', '(2015–2020)', '(2016–2022)', '(2017– )', '(2018–2020)', '(2017– )', '(2014–2019)', '(2009–2015)', '(1997– )', '(2013–2021)', '(2013–2015)', '(2019–2024)', '(2014– )', '(2016–2019)', '(2004–2012)', '(2015–2022)', '(2013–2017)', '(2017–2019)', '(2017–2021)', '(2017–2022)', '(2016–2022)', '(2016–2020)', '(2017–2018)', '(2018–2020)', '(2017–2019)', '(2011–2015)', '(2016–2018)', '(2012–2018)', '(2017)', '(2017–2019)', '(2018–2019)', '(2008–2015)', '(2016–2023)', '(2019)', '(2015–2019)', '(2013–2017)', '(2017–2019)', '(2005– )', '(2015–2019)', '(2018)']
['4,189 min', '51 min', '44 min', '60 min', '43 min', '59 min', '45 min', '41 min', '43 min', '42 min', '70 min', '5,702 min', '60 min', '88 min', '44 min', '44 min', '43 min', '60 min', '3,030 min', '42 min', '44 min', '44 min', '43 min', '41 min', '22 min', '60 min', '49 min', '54 min', '5,280 min', '4,576 min', '44 min', '49 min', '45 min', '43 min', '42 min', '60 min', '42 min', '62 min', '56 min', '22 min', '23 min', '42 min', '25 min', '3,804 min', '1,455 min', '60 min', '45 min', '46 min', '22 min', '45 min', '45 min', '5,076 min', '44 min', '22 min', '43 min', '44 min', '2,109 min', '7,788 min', '42 min', '44 min', '55 min', '42 min', '42 min', '60 min', '60 min', '41 min', '60 min', '44 min', '22 min', '22 min', '43 min', '60 min', '55 min', '60 min', '45 min', '3,154 min', '45 min', '53 min', '30 min', '42 min', '45 min', '22 min', '55 min', '45 min', '60 min', '44 min', '55 min', '43 min', '50 min', '356 min', '45 min', '43 min', '58 min', '330 min', '42 min', '42 min', '50 min', '42 min', '45 min', '572 min']
['Action, Adventure, Drama', 'Drama, Fantasy, Horror', 'Drama, Horror, Thriller', 'Drama, Mystery, Thriller', 'Drama, Mystery, Sci-Fi', 'Comedy, Crime, Drama', 'Crime, Drama, Mystery', 'Drama, Romance', 'Action, Adventure, Drama', 'Action, Adventure, Crime', 'Action, Crime, Drama', 'Comedy, Romance', 'Drama, Mystery, Sci-Fi', 'Crime, Drama, Mystery', 'Action, Adventure, Drama', 'Drama, Mystery, Romance', 'Drama, Fantasy, Horror', 'Drama, Horror, Sci-Fi', 'Crime, Drama, Thriller', 'Crime, Drama, Fantasy', 'Drama, Fantasy, Horror', 'Action, Crime, Drama', 'Crime, Drama, Mystery', 'Action, Drama, Fantasy', 'Animation, Comedy', 'Adventure, Fantasy, Romance', 'Biography, Crime, Drama', 'Action, Crime, Drama', 'Comedy, Romance', 'Comedy, Drama, Romance', 'Comedy, Drama', 'Crime, Drama, Thriller', 'Drama, Fantasy, Horror', 'Action, Adventure, Drama', 'Drama, Romance', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Comedy, Drama, Romance', 'Animation, Adventure, Comedy', 'Action, Drama, Fantasy', 'Adventure, Comedy, Crime', 'Drama', 'Crime, Drama, Mystery', 'Crime, Drama, Thriller', 'Comedy, Drama', 'Comedy, Drama', 'Comedy, Romance', 'Action, Adventure, Drama', 'Crime, Drama, Romance', 'Crime, Drama, Mystery', 'Drama, Horror, Sci-Fi', 'Animation, Comedy', 'Crime, Drama, Mystery', 'Adventure, Drama, Fantasy', 'Crime, Drama', 'Drama, Mystery', 'Crime, Drama, Mystery', 'Drama, Sci-Fi, Thriller', 'Crime, Drama, Mystery', 'Action, Crime, Drama', 'Action, Adventure, Drama', 'Drama, Sci-Fi, Thriller', 'Drama, Fantasy, Horror', 'Drama', 'Comedy', 'Comedy, Drama, Music', 'Animation, Comedy', 'Comedy, Crime', 'Drama, Mystery, Sci-Fi', 'Action, Adventure, Comedy', 'Crime, Drama, Mystery', 'Drama, Fantasy, Mystery', 'Comedy, Drama, Mystery', 'Crime, Drama', 'Drama, Horror, Mystery', 'Action, Crime, Drama', 'Comedy, Drama', 'Drama', 'Comedy, Drama, Romance', 'Comedy, Drama, Fantasy', 'Action, Adventure, Crime', 'Drama, Sci-Fi, Thriller', 'Crime, Drama, Mystery', 'Drama, Mystery, Thriller', 'Action, Crime, Drama', 'Drama, Thriller', 'Action, Adventure, Crime', 'Crime, Drama, Mystery', 'Comedy, Drama, Thriller', 'Crime, Drama, Mystery', 'Biography, Drama, History', 'Drama, History, Thriller', 'Comedy, Crime, Drama', 'Drama', 'Adventure, Comedy, Drama', 'Crime, Drama, Mystery', 'Comedy, Crime, Drama', 'Drama, Horror, Mystery']
['9.2', '8.7', '8.1', '7.5', '7.6', '8', '6.5', '7.6', '7.5', '7.5', '8.2', '8.2', '8.7', '9.1', '8.5', '7.4', '7.7', '8', '9.5', '8.1', '8.4', '8.3', '8.1', '7.7', '8.7', '7.7', '8.8', '8.6', '8.9', '8.3', '8.4', '8.5', '8.3', '6.2', '7.5', '8.2', '7.8', '8.5', '7.9', '8.5', '9.1', '6.5', '8', '8.7', '8.7', '7.2', '8.3', '8.5', '7.8', '7.5', '7.7', '8.7', '6.8', '8.2', '7.9', '8.3', '8.8', '8.7', '6.7', '8.3', '8.3', '7.3', '6.8', '8.4', '7.4', '8', '7.9', '6.8', '8.7', '8.4', '6.5', '7.9', '8.9', '7.8', '7.6', '9', '8.1', '8.5', '8.2', '7.3', '8.7', '8.2', '6.4', '6.3', '8.6', '7.8', '7.3', '7.7', '7.2', '8.4', '6.5', '8.2', '8.6', '9.3', '7.8', '7.5', '7.8', '8.1', '7', '8.6']
['2,226,486', '1,293,463', '1,056,206', '310,108', '269,228', '315,978', '152,846', '332,542', '364,626', '442,601', '514,379', '848,314', '619,843', '975,172', '566,995', '175,734', '342,142', '337,546', '2,067,085', '346,872', '471,936', '567,534', '162,996', '160,102', '428,492', '233,943', '457,239', '464,813', '1,059,658', '716,175', '459,400', '409,441', '144,775', '128,316', '188,233', '160,694', '238,223', '524,263', '223,586', '467,358', '579,287', '68,784', '212,808', '523,661', '427,407', '88,534', '336,986', '270,111', '240,424', '223,813', '288,162', '751,655', '140,464', '358,043', '273,774', '582,552', '618,461', '495,234', '63,230', '115,539', '355,918', '77,884', '109,004', '252,489', '105,585', '108,896', '57,104', '153,917', '398,527', '347,326', '110,974', '267,301', '616,032', '112,219', '136,797', '617,682', '114,944', '257,422', '100,534', '24,423', '153,825', '181,804', '137,513', '40,529', '321,574', '123,719', '137,570', '78,583', '114,360', '218,161', '31,719', '196,197', '239,550', '832,475', '72,962', '53,273', '65,355', '213,156', '44,371', '278,003']

In [19]:
print(len(rank),len(show),len(year),len(run_time),len(genre),len(ratings),len(votes))

100 100 100 100 100 100 100

In [20]:
df = pd.DataFrame({'RANK': rank, 'SHOW NAME': show, 'YEAR SPAN': year, 'RUN TIME': run_time, 'GENRE': genre, 'RATINGS': ratings, 'VOTES': votes})
df

,RANK,SHOW NAME,YEAR SPAN,RUN TIME,GENRE,RATINGS,VOTES
0,1,Game of Thrones,(2011–2019),"4,189 min","Action, Adventure, Drama",9.2,"2,226,486"
1,2,Stranger Things,(2016–2025),51 min,"Drama, Fantasy, Horror",8.7,"1,293,463"
2,3,The Walking Dead,(2010–2022),44 min,"Drama, Horror, Thriller",8.1,"1,056,206"
3,4,13 Reasons Why,(2017–2020),60 min,"Drama, Mystery, Thriller",7.5,"310,108"
4,5,The 100,(2014–2020),43 min,"Drama, Mystery, Sci-Fi",7.6,"269,228"
...,...,...,...,...,...,...,...
95,96,Reign,(2013–2017),42 min,Drama,7.5,"53,273"
96,97,A Series of Unfortunate Events,(2017–2019),50 min,"Adventure, Comedy, Drama",7.8,"65,355"
97,98,Criminal Minds,(2005– ),42 min,"Crime, Drama, Mystery",8.1,"213,156"
98,99,Scream: The TV Series,(2015–2019),45 min,"Comedy, Crime, Drama",7,"44,371"
99,100,The Haunting of Hill House,(2018),572 min,"Drama, Horror, Mystery",8.6,"278,003"

# QUESTION 8

In [29]:
driver = webdriver.Chrome()
#To load url
driver.get("https://archive.ics.uci.edu/")
#To maximize window 
driver.maximize_window()
action = ActionChains(driver)

time.sleep(5)
agree_ele=driver.find_element(By.XPATH,"//div[@class='alert fixed bottom-0']/div[2]/button")
agree_ele.click()

#To view all datasets
dataset_ele=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]")
dataset_ele.click()


#creating empty list for all attributes
d_name=[]
d_type=[]
task=[]
att_type=[]
instances=[]
att_count=[]
year=[]

page=[1,2,3,4,5,6,7,8,9,10]

for i in page:
    
    if(i==1):
        time.sleep(5)
        expand_ele=driver.find_element(By.XPATH,"(//div[@class='swap'])[2]")
        expand_ele.click()
    else:
        time.sleep(3)
        expand_ele=driver.find_element(By.XPATH,"(//div[@class='swap'])[2]")
        expand_ele.click()
        time.sleep(3)
        expand_ele.click()

    time.sleep(5)
    d_name_ele=driver.find_elements(By.XPATH,"//h2[@class='truncate text-primary']/a")
    for i in d_name_ele:
        x=i.text
        d_name.append(x)
    
    d_type_ele=driver.find_elements(By.XPATH,"//div[@class='my-2 hidden gap-4 md:grid grid-cols-12']/div[2]/span")
    for i in d_type_ele:
        x=i.text
        d_type.append(x)
        
    task_ele=driver.find_elements(By.XPATH,"//div[@class='my-2 hidden gap-4 md:grid grid-cols-12']/div[1]/span")
    for i in task_ele:
        x=i.text
        task.append(x)
    
    instances_ele=driver.find_elements(By.XPATH,"//div[@class='my-2 hidden gap-4 md:grid grid-cols-12']/div[3]/span")
    for i in instances_ele:
        x=i.text
        instances.append(x)
        
    att_count_ele=driver.find_elements(By.XPATH,"//div[@class='my-2 hidden gap-4 md:grid grid-cols-12']/div[4]/span")
    for i in att_count_ele:
        x=i.text.replace('Features','')
        att_count.append(x)
        
    year_ele=driver.find_elements(By.XPATH,"//tbody[@class='border']/tr/td[3]")
    for i in year_ele:
        x=i.text
        year.append(x)
    
    att_type_ele=driver.find_elements(By.XPATH,"//tbody[@class='border']/tr/td[2]")
    for i in att_type_ele:
        x=i.text
        att_type.append(x)
    
    time.sleep(5)
    next_page_ele=driver.find_element(By.XPATH,"//button[@aria-label='Next Page']")
    #action.move_to_element(next_page_ele).click().perform()
    next_page_ele.click()
    time.sleep(3)

print(d_name)
print(d_type)
print(task)
print(att_type)
print(instances)
print(att_count)
print(year)

['Iris', 'Heart Disease', 'Adult', 'Wine', 'Breast Cancer Wisconsin (Diagnostic)', 'Diabetes', 'Dry Bean Dataset', 'Car Evaluation', 'Wine Quality', 'Bank Marketing', 'Mushroom', 'Rice (Cammeo and Osmancik)', 'Abalone', 'Census Income', 'Student Performance', 'Statlog (German Credit Data)', 'Breast Cancer', 'Automobile', 'Auto MPG', 'Breast Cancer Wisconsin (Original)', 'Online Retail', "Predict students' dropout and academic success", 'Spambase', 'Glass Identification', 'Thyroid Disease', 'Credit Approval', 'Optical Recognition of Handwritten Digits', 'Zoo', 'Online Retail II', 'Air Quality', 'default of credit card clients', 'Lung Cancer', 'Liver Disorders', 'Human Activity Recognition Using Smartphones', 'Bike Sharing Dataset', 'Covertype', 'Ionosphere', 'Letter Recognition', 'Internet Advertisements', 'SMS Spam Collection', 'Hepatitis', 'Online Shoppers Purchasing Intention Dataset', 'Computer Hardware', 'Individual household electric power consumption', 'Congressional Voting Records', 'MAGIC Gamma Telescope', 'Forest Fires', 'Image Segmentation', 'Yeast', 'Connectionist Bench (Sonar, Mines vs. Rocks)', 'Pen-Based Recognition of Handwritten Digits', 'Estimation of obesity levels based on eating habits and physical condition', 'Tic-Tac-Toe Endgame', 'Diabetes 130-US hospitals for years 1999-2008', 'Heart failure clinical records', 'Nursery', 'Arrhythmia', 'Statlog (Australian Credit Approval)', 'Breast Cancer Wisconsin (Prognostic)', 'Balance Scale', 'seeds', 'Soybean (Large)', 'Real estate valuation data set', 'EEG Database', 'Reuters-21578 Text Categorization Collection', 'Statlog (Heart)', 'Dermatology', 'Statlog (Landsat Satellite)', 'Seoul Bike Sharing Demand', 'Apartment for rent classified', 'Statlog (Shuttle)', 'Energy efficiency', 'Ecoli', 'Wholesale customers', 'Solar Flare', 'Movie', 'Statlog (Vehicle Silhouettes)', 'Insurance Company Benchmark (COIL 2000)', 'ISOLET', 'Contraceptive Method Choice', 'Concrete Compressive Strength', 'Soybean (Small)', 'Molecular Biology (Promoter Gene Sequences)', 'Statlog Project', 'Parkinsons', 'Waveform Database Generator (Version 1)', 'AI4I 2020 Predictive Maintenance Dataset', 'Online News Popularity', 'Flags', 'Anonymous Microsoft Web Data', 'Lenses', 'Horse Colic', 'CMU Face Images', 'Protein Data', "MONK's Problems", 'KDD Cup 1999 Data', 'CDC Diabetes Health Indicators', 'Molecular Biology (Splice-junction Gene Sequences)', "Haberman's Survival", 'ElectricityLoadDiagrams20112014']
['Tabular', 'Multivariate', 'Multivariate', 'Tabular', 'Multivariate', 'Multivariate, Time-Series', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Tabular', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate, Sequential, Time-Series', 'Tabular', 'Multivariate', 'Multivariate', 'Multivariate, Domain-Theory', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate, Sequential, Time-Series, Text', 'Multivariate, Time-Series', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate, Time-Series', 'Univariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate, Text, Domain-Theory', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate, Time-Series', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate, Time-Series', 'Text', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', '', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Multivariate', 'Sequential, Domain-Theory', 'Other', 'Multivariate', 'Multivariate, Data-Generator', 'Multivariate, Time-Series', 'Multivariate', 'Multivariate', 'null', 'Multivariate', 'Multivariate', 'Image', '', 'Multivariate', 'Multivariate', 'Tabular, Multivariate', 'Sequential, Domain-Theory', 'Multivariate', 'Time-Series']
['Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification, Regression', 'Classification', 'Classification', 'Classification', 'Classification, Regression', 'Classification', 'Classification, Regression', 'Classification', 'Classification', 'Regression', 'Regression', 'Classification', 'Classification, Clustering', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification, Regression, Clustering', 'Regression', 'Classification', 'Classification', 'Regression', 'Classification, Clustering', 'Regression', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification, Clustering', 'Classification', 'Classification, Clustering', 'Regression', 'Regression, Clustering', 'Classification', 'Classification', 'Regression', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification, Regression, Clustering', 'Classification', 'Classification, Clustering', 'Classification, Regression, Clustering', 'Classification', 'Classification', 'Classification', 'Classification, Regression', 'Classification', 'Classification, Clustering', 'Classification', 'Regression', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Regression', 'Classification, Regression, Clustering', 'Classification', 'Classification, Regression', 'Classification', 'Classification, Clustering', 'Regression', '', 'Classification', 'Regression, Description', 'Classification', 'Classification', 'Regression', 'Classification', 'Classification', 'Other', 'Classification', 'Classification', 'Classification, Regression, Causal-Discovery', 'Classification, Regression', 'Classification', 'Recommender-Systems', 'Classification', 'Classification', 'Classification', '', 'Classification', 'Classification', 'Classification', 'Classification', 'Classification', 'Regression, Clustering']
['Real', 'Categorical, Integer, Real', 'Categorical, Integer', 'Integer, Real', 'Real', 'Categorical, Integer', 'Integer, Real', 'Categorical', 'Real', 'Categorical, Integer', 'Categorical', 'Real', 'Categorical, Integer, Real', 'Categorical, Integer', 'Integer', 'Categorical, Integer', 'Categorical', 'Categorical, Integer, Real', 'Real, Categorical, Integer', 'Integer', 'Integer, Real', 'N/A', 'Integer, Real', 'Real', 'Categorical, Real', 'Categorical, Integer, Real', 'Integer', 'Categorical, Integer', 'Integer, Real', 'Real', 'Integer, Real', 'Integer', 'Categorical, Integer, Real', '', 'Integer, Real', 'Categorical, Integer', 'Integer, Real', 'Integer', 'Categorical, Integer, Real', 'Real', 'Categorical, Integer, Real', 'Integer, Real', 'Integer', 'Real', 'Categorical', 'Real', 'Real', 'Real', 'Real', 'Real', 'Integer', 'Integer', 'Categorical', 'Categorical, Integer', 'Integer, Real', 'Categorical', 'Categorical, Integer, Real', 'Categorical, Integer, Real', 'Real', 'Categorical', 'Real', 'Categorical', 'Integer, Real', 'Categorical, Integer, Real', 'Categorical', 'Categorical, Real', 'Categorical, Integer', 'Integer', 'Integer, Real', 'N/A', 'Integer', 'Integer, Real', 'Real', 'Integer', 'Categorical', 'N/A', 'Integer', 'Categorical, Integer', 'Real', 'Categorical, Integer', 'Real', 'Categorical', 'Categorical', '', 'Real', 'Real', 'Real', 'Integer, Real', 'Categorical, Integer', 'Categorical', 'Categorical', 'Categorical, Integer, Real', 'Integer', 'N/A', 'Categorical', 'Categorical, Integer', 'Categorical, Integer', 'Categorical', 'Integer', 'Real']
['150 Instances', '303 Instances', '48.84K Instances', '178 Instances', '569 Instances', '1 Instances', '13.61K Instances', '1.73K Instances', '4.9K Instances', '45.21K Instances', '8.12K Instances', '3.81K Instances', '4.18K Instances', '48.84K Instances', '649 Instances', '1K Instances', '286 Instances', '205 Instances', '398 Instances', '699 Instances', '541.91K Instances', '4.42K Instances', '4.6K Instances', '214 Instances', '7.2K Instances', '690 Instances', '5.62K Instances', '101 Instances', '1.07M Instances', '9.36K Instances', '30K Instances', '32 Instances', '345 Instances', '10.3K Instances', '17.39K Instances', '581.01K Instances', '351 Instances', '20K Instances', '3.28K Instances', '5.57K Instances', '155 Instances', '12.33K Instances', '209 Instances', '2.08M Instances', '435 Instances', '19.02K Instances', '517 Instances', '2.31K Instances', '1.48K Instances', '208 Instances', '10.99K Instances', '2.11K Instances', '958 Instances', '101.77K Instances', '299 Instances', '12.96K Instances', '452 Instances', '690 Instances', '198 Instances', '625 Instances', '210 Instances', '307 Instances', '414 Instances', '122 Instances', '21.58K Instances', '270 Instances', '366 Instances', '6.44K Instances', '8.76K Instances', '10K Instances', '58K Instances', '768 Instances', '336 Instances', '440 Instances', '1.39K Instances', '10K Instances', '946 Instances', '9K Instances', '7.8K Instances', '1.47K Instances', '1.03K Instances', '47 Instances', '106 Instances', '1 Instances', '197 Instances', '5K Instances', '10K Instances', '39.8K Instances', '194 Instances', '37.71K Instances', '24 Instances', '368 Instances', '640 Instances', '', '432 Instances', '4M Instances', '253.68K Instances', '3.19K Instances', '306 Instances', '370 Instances']
['4 ', '13 ', '14 ', '13 ', '30 ', '20 ', '16 ', '6 ', '12 ', '17 ', '22 ', '7 ', '8 ', '14 ', '33 ', '20 ', '9 ', '25 ', '7 ', '9 ', '8 ', '36 ', '57 ', '9 ', '5 ', '15 ', '64 ', '16 ', '8 ', '15 ', '24 ', '56 ', '5 ', '561 ', '16 ', '54 ', '34 ', '16 ', '1.56K ', '', '19 ', '18 ', '9 ', '9 ', '16 ', '11 ', '', '19 ', '8 ', '60 ', '16 ', '17 ', '9 ', '47 ', '12 ', '8 ', '', '14 ', '', '4 ', '7 ', '35 ', '7 ', '', '5 ', '', '', '36 ', '14 ', '22 ', '8 ', '8 ', '8 ', '8 ', '10 ', '', '18 ', '86 ', '617 ', '', '9 ', '35 ', '58 ', '', '', '21 ', '14 ', '61 ', '30 ', '294 ', '4 ', '27 ', '', '', '6 ', '42 ', '21 ', '61 ', '', '140.26K ']
['7/1/1988', '7/1/1988', '5/1/1996', '7/1/1991', '11/1/1995', 'N/A', '9/14/2020', '6/1/1997', '10/7/2009', '2/14/2012', '4/27/1987', '10/6/2019', '12/1/1995', '5/1/1996', '11/27/2014', '11/17/1994', '7/11/1988', '5/19/1987', '7/7/1993', '7/15/1992', '11/6/2015', '12/13/2021', '7/1/1999', '9/1/1987', '1/1/1987', 'N/A', '7/1/1998', '5/15/1990', '9/21/2019', '3/23/2016', '1/26/2016', '5/1/1992', '5/15/1990', '12/10/2012', '12/20/2013', '8/1/1998', '1/1/1989', '1/1/1991', '7/1/1998', '6/22/2012', '11/1/1988', '8/31/2018', '10/1/1987', '8/30/2012', '4/27/1987', '5/1/2007', '2/29/2008', '11/1/1990', '9/1/1996', 'N/A', '7/1/1998', '8/27/2019', '8/19/1991', '5/3/2014', '2/5/2020', '6/1/1997', '1/1/1998', 'N/A', '12/1/1995', '4/22/1994', '9/29/2012', '7/11/1988', '8/18/2018', '10/13/1999', '9/26/1997', 'N/A', '1/1/1998', '2/13/1993', '3/1/2020', '12/26/2019', 'N/A', '11/30/2012', '9/1/1996', '3/31/2014', '3/1/1989', '7/7/1999', 'N/A', '7/3/2000', '9/12/1994', '7/7/1997', '8/3/2007', '1/1/1987', '6/30/1990', '10/1/1992', '6/26/2008', '11/10/1988', '8/30/2020', '5/31/2015', '5/15/1990', '11/1/1998', '8/1/1990', '8/6/1989', '6/24/1999', 'N/A', '10/1/1992', '1/1/1999', '9/26/2023', '1/1/1992', '3/4/1999', '3/13/2015']

In [30]:
print(len(d_name),len(d_type),len(task),len(att_type),len(instances),len(att_count),len(year))

100 100 100 100 100 100 100

In [31]:
df = pd.DataFrame({'DATASET NAME': d_name, 'DATA TYPE': d_type, 'TASK': task, 'ATTRIBUTE TYPE': att_type, 'NO. OF INSTANCES': instances, 'NO. OF ATTRIBUTES': att_count, 'YEAR': year})
df

,DATASET NAME,DATA TYPE,TASK,ATTRIBUTE TYPE,NO. OF INSTANCES,NO. OF ATTRIBUTES,YEAR
0,Iris,Tabular,Classification,Real,150 Instances,4,7/1/1988
1,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303 Instances,13,7/1/1988
2,Adult,Multivariate,Classification,"Categorical, Integer",48.84K Instances,14,5/1/1996
3,Wine,Tabular,Classification,"Integer, Real",178 Instances,13,7/1/1991
4,Breast Cancer Wisconsin (Diagnostic),Multivariate,Classification,Real,569 Instances,30,11/1/1995
...,...,...,...,...,...,...,...
95,KDD Cup 1999 Data,Multivariate,Classification,"Categorical, Integer",4M Instances,42,1/1/1999
96,CDC Diabetes Health Indicators,"Tabular, Multivariate",Classification,"Categorical, Integer",253.68K Instances,21,9/26/2023
97,Molecular Biology (Splice-junction Gene Sequen...,"Sequential, Domain-Theory",Classification,Categorical,3.19K Instances,61,1/1/1992
98,Haberman's Survival,Multivariate,Classification,Integer,306 Instances,,3/4/1999
99,ElectricityLoadDiagrams20112014,Time-Series,"Regression, Clustering",Real,370 Instances,140.26K,3/13/2015